### ISSUE TITLE
Authentication research

### ISSUE THREAD

**Issue by sharonwarner** [cagov/unemployment#101]
Details can be found here: https://docs.google.com/document/d/1pNPa5LWPVeX9zWRdpslw3wsQKMz4iaMgVzDXVWPhBPo/edit#heading=h.ib7may7dzxnp

**Comment by idealisms** [comment]
The questions to be answered are: What is involved with integrating with BPO? If not using BPO, what identifying information would we need?

**Comment by sharonwarner** [comment]
We came to a solution with EDD and ISO folks. We're going to build a public link to the application. On the application homepage, users will need to input their SSN, EDDCAN ID, last name, and one other field that EDD will determine. We'll also include a reCAPTCHA.
