### ISSUE TITLE
Set Cache-Control header TTL to over 30 days

### ISSUE THREAD

**Issue by kalvinwang** [cagov/unemployment#139]
This issue depends on #189

Original situation: Static assets have a TTL of under 30s, which adds 700KB on refreshes after 30s

We then bumped up the TTL to 12-24 hours (we set the ceiling at 1 day in Azure, but Akamai's TTL is dynamic...) 

and now the content-encoding header is set ([reference](https://web.dev/uses-long-cache-ttl/))

New situation: Google Lighthouse still gives "red triangle" warnings to all assets; from experimenting, it seems like a 15-day TTL will give "orange square" warnings, and perhaps over 30-day TTL will give the desired "gray circle" neutral bullets.

But we don't want to increase the cache beyond 1 day because we don't have content hashing yet for json and svg, only css and js. Once we do (see #189) we should increase the TTL to 30+ days.

This issue was originally half of #139

**Comment by idealisms** [comment]
I was poking around Google Analytics and saw that the guide was one of the slower pages to load.  It uses [Google Page Speed Insights](https://developers.google.com/speed/pagespeed/insights/?utm_source=analytics&tab=mobile&url=https%3A%2F%2Fedd.ca.gov%2Fguide%2Fbenefits) (how/why is this different from lighthouse?) and suggested the same thing.

Adding text compression to js and css files should be an easy win. I poked around on [Azure](https://portal.azure.com/#@digitalca.onmicrosoft.com/resource/subscriptions/005fa005-b981-47d8-8b39-5b82adf6569c/resourceGroups/RG-CDT-PUB-VIP-BNSCN-W-P-002/providers/Microsoft.Web/sites/AS-CDT-PUB-VIP-BNSCN-WL-P-002/appServices) to see if I could find the CDN to turn it on, but couldn't find it. Is this something we have to ask CDT to do or am I looking in the wrong place?

**Comment by kalvinwang** [comment]
@idealisms CDT showed me where to do it earlier this week, but when I tried to apply the changes, I don't have permission to do it. I'll add you to the email thread. I'm planning to add "css, ico, svg, js" to the list of file extensions to cache for 1 day. We hash our CSS and JS files so they'll expire on new deploys.

**Comment by kalvinwang** [comment]
I just tried to make this change in Azure (from 1 to 30 days) but don't have permission, so I've emailed OET/CDT to request the change.

**Comment by kalvinwang** [comment]
This is complete 

![image](https://user-images.githubusercontent.com/82277/93898796-a11ad780-fcc1-11ea-9c50-5d94e9e9871d.png)
