### ISSUE TITLE
Add security scan

### ISSUE THREAD

**Issue by sharonwarner** [cagov/unemployment#150]
- [ ] Research whether we should use Snyk or CDT's existing scan
- [ ] Implement preferred approach

https://support.snyk.io/hc/en-us/articles/360004032117-GitHub-integration

**Comment by kalvinwang** [comment]
We've been making use of Dependabot, which is integrated into Github, to detect vulnerabilities in our dependencies. Snyk does the same thing, and I couldn't find any evidence online that they do it any better. For code scanning, it's a Snyk feature "coming soon", but Github has a solution for that as well, which I've made an issue to look into here: #636. I'll close this ticket for now.
