### ISSUE TITLE
Update Certification guidance

### ISSUE THREAD

**Issue by mthong** [cagov/unemployment#164]
From Mai Do's email, sent Friday afternoon, 5/8/2020:

`We are removing the language from our website about suspending the requirement for UI certifications Monday morning. We are not replacing it with any messaging. Can you also update the UI Guide to remove any language about this? Sorry for the short notice.`

**Comment by mkhandekar** [comment]
So basically this ask is to remove the _Notes_ and "When you are required to certify..."  -- yes? 

If so, I'm happy to give this the go-ahead, and I'll make the same changes in our Active Draft google doc too.

On **After you submit your application**, remove the content in the pink boxes:

![Screenshot 2020-05-11 21 21 08](https://user-images.githubusercontent.com/1598889/81631427-7c3a5d80-93cd-11ea-9042-00d90c870019.png)

---  

On **Receive your benefits**, remove the content in the pink boxes:

![Screenshot 2020-05-11 21 23 21](https://user-images.githubusercontent.com/1598889/81631621-ddfac780-93cd-11ea-9b45-e3e86d31fc20.png)

**Comment by mthong** [comment]
Yes, that's my understanding that they simply asked for us to remove the content.
