### ISSUE TITLE
Onboard Meghan Casey

### ISSUE THREAD

**Issue by mkhandekar** [cagov/unemployment#174]
Tasks, sessions, readings for Meghan 

- [x] Program context @mthong, Weds
- [x] Stakeholder landscape @mthong, Weds
- [x] What we've done so far @mthong, Weds
- [x] Brief tour of key documents in our [Table of Contents](https://docs.google.com/document/d/1eii-1WXB5dBUtW5i-JxqpknThP6-iFubMAkka-fdvRU/) @mthong, Weds. 
  - [x] A special nudge towards reading the documents under Project Context (Nava Scope of Work and Policy sections), and the highlighted in green items under Design & Research.
- [x] Evolution of the Guide from a design (content, research, design) stand point @mkhandekar, Thurs 
- [x] Add to Google drives @mkhandekar  
- [x] Add to Github @mkhandekar 
- [x] Add to Figma (visual design for both Guide and Certification) @nguyen-tina 
  * Note: this is where the Nava design team left comments related to short <> long term recommendations 
- [x] Confirm you can view [this LucidChart ](https://www.lucidchart.com/documents/edit/933c2728-b8da-4eeb-afb7-6b7eab4843a1/dIqQw1yHlRId )

**Comment by meghscase** [comment]
requested access to LucidChart

**Comment by nguyen-tina** [comment]
It should be approved for edit + comment access!
