### ISSUE TITLE
Content | Draft open questions and initial ideas related to Guide, EDD site and content governance

### ISSUE THREAD

**Issue by mkhandekar** [cagov/unemployment#176]
@meghscase the main priorities for this sprint will be to onboard (#174) and as you get familiar with the Guide, the PAB team and their process, and the EDD site in general, is a draft of open questions and initial ideas related to Guide, EDD site and content governance. 

Some questions we can answer, others we will set aside for PAB.

Later this week or early next week, we can check in with @danachis to align on how and when we should frame these questions and conversations with PAB.

Document: https://docs.google.com/document/d/12HhGfgtUqsquyf-oAee2zCh3-lGB1_GJmD7wZE2LLvQ/edit#

**Comment by meghscase** [comment]
Here's an initial list of questions: 

Who will be working on content and what are their skillsets?
How does PAB interface with SMEs, etc., to create content?
What's the current process for creating new content?
What's the current process for updating existing content?
What's the current process for making urgent updates to content?
What are the current challenges with content creation and management?
What are the current problems and opportunities for existing content in the guide? Why are the problems problems (e.g., SMEs don't have time to work with us; business partners don't care about online content; we don't have people working on content with the right experience)
How often do you envision needing to update the content?
What will trigger those updates?
What kind of content tools, templates, guidelines, etc., do you have currently?
Are they used? If no, why not?
How do you anticipate measuring success of the guide content?

@mkhandekar

**Comment by meghscase** [comment]
Sounds good. I wanted to get my initial questions documented somewhere.

**Comment by meghscase** [comment]
Document with questions and recommendations: https://docs.google.com/document/d/12HhGfgtUqsquyf-oAee2zCh3-lGB1_GJmD7wZE2LLvQ/edit#
