### ISSUE TITLE
Design | Certification | design prototype V2

### ISSUE THREAD

**Issue by mkhandekar** [cagov/unemployment#178]
A slightly bigger effort to prototype a set of screens for recertification that we can usability test with users in Sprint 4.
* Based on updated [EDD Retroactive Cert Prototype Design Brief](https://docs.google.com/document/d/1v-xLveyNdej_ae6l3sVF-2uzPfKeDrCwWaHDZXHKoDc/edit#heading=h.do1zau31g0ya)
* Dependencies: #91

**Comment by mkhandekar** [comment]
@nguyen-tina Could you add a link to the Figma file and/or a PDF export of the current state, and then close this issue?

**Comment by nguyen-tina** [comment]
[Retroactive Certification – Prototype v2.pdf](https://github.com/cagov/unemployment/files/4684246/Retroactive.Certification.Prototype.v2.pdf)

This is where the prototype is at this stage!
