### ISSUE TITLE
InfoImage research

### ISSUE THREAD

**Issue by sharonwarner** [cagov/unemployment#181]

**Comment by mthong** [comment]
The goal of this task is to scope the feasibility and level of effort of integrating a document uploader with EDD's document management system, InfoImage. 

The desired outcome from this task is an assessment of:
1. Whether it would be feasible for us to integrate a Vermont-like uploader tool with InfoImage
2. High level rough estimate of the level of effort (E.g. weeks of work assuming 2 engineers) for integrating with InfoImage 

I will check with Eric on whether he needs a rough level of effort for adapting the uploader itself (E.g. how much could we reuse from Vermont, how much would we need to build from scratch) 

Bonus points: 
* Identify risks or dependencies that would need to be investigated further

References: 
- [ODI's draft scope of work](https://docs.google.com/document/d/15HjfC74i0W32Fso_7KtJI0ARvj_hryqGWV5gXGjO9c8/edit?usp=sharing)
- Demo of uploader functionality as it currently exists in [SDI Online ](https://drive.google.com/open?id=1WFu7NUI6Qs1noXaqAm2N-N1Iyva_Bwul), EDD's disability insurance system. Slides 24-26 of this deck appear to document the technical interface for InfoImage. 

Tony can provide more details from an internal doc if needed.

**Comment by idealisms** [comment]
[Initial research](https://docs.google.com/document/d/1-dkvm1GGtoHvSOln0NGSgJJM9Gztyc9SkNL9ComhgPE/edit#)

**Comment by mthong** [comment]
Update for @sharonwarner: as mentioned in my comment above, I confirmed with Eric that we should come up with a rough estimate for adapting the uploader itself (E.g. how much could we reuse from Vermont, how much would we need to build from scratch). I'll make this task part of a separate uploader scoping ticket, #173, and add you as an assignee.
