### ISSUE TITLE
Support ODI in developing Service Blueprint | Sprint 3

### ISSUE THREAD

**Issue by nguyen-tina** [cagov/unemployment#191]
Every Monday at 1 PM PST / 4 PM EST, Dana is leading a co-working session with EDD to create a service blueprint. 

This sprint, Design will help to prepare for the meeting as well as attending it to collaborate and co-create the Blueprint.

Meghana: `.5 points`
Tina: `.5 points`
Total: `half a day`

- [x] Create template for service blueprint to be used by group

**Comment by mkhandekar** [comment]
Service blueprint template to be used by group can be found [here](https://docs.google.com/spreadsheets/d/1lfEY0VY6WbTs5Bd-GAJ8jDMsIuOJ0-Ojmj9PIKY_o40/edit#gid=1909024384) (google spreadsheet).

**Comment by mkhandekar** [comment]
We supported last sprint :)
