### ISSUE TITLE
Broken "Receive your benefits" link on tab 1

### ISSUE THREAD

**Issue by sharonwarner** [cagov/unemployment#196]
The last paragraph in this section should include a link to the "Receive your benefits" tab. This should be tested on both the English and Spanish pages.

<img width="769" alt="Screen Shot 2020-05-14 at 1 21 04 PM" src="https://user-images.githubusercontent.com/4306128/81965282-d3b31600-95e5-11ea-9601-959a2ef6ec8f.png">

**Comment by kalvinwang** [comment]
Hm, I wonder how this broke... I actually tested it specifically after my recent PRs, I thought.
