### ISSUE TITLE
Add new PEUC information to the Guide

### ISSUE THREAD

**Issue by mthong** [cagov/unemployment#202]
On Friday, May 15, [EDD released new information](https://www.edd.ca.gov/About_EDD/pdf/news-20-17.pdf
) about implementing Pandemic Emergency Unemployment Compensation (PEUC), which provides an additional 13 weeks of benefits for people receiving UI benefits between March 29 and December 26, 2020. 

The "[More Resources" page of the Guide](https://unemployment.edd.ca.gov/guide/more-resources) currently states:
`Note: We are still working to implement the PEUC program. Please continue to monitor our website for instructions on next steps for the PEUC program.`

Now that there is new information (see 2nd and 3rd pages of the news release), we should at minimum link to the news release, or ideally massage the news release content into actionable guidance.

**Comment by meghscase** [comment]
I think for sure, link to news release immediately. I'd like to suggest eventually a different approach to resources or at least making sure the information is provided in context of the page they are on as well. Hopefully this sprint, I can make some recommendations for consideration.

**Comment by mthong** [comment]
@meghscase Yesterday(5/26/20) I forwarded an email to you and @mkhandekar that includes the proposed content that EDD Public Affairs provided for talking about PEUC on the Guide. Now that we have that, I think that would be the starting point for this task.

**Comment by meghscase** [comment]
@mthong @mkhandekar : I made some suggestions to the edits provided by EDD. How to we go about getting those approved? There are a couple things that need to be confirmed in my plain language suggestions. 

https://docs.google.com/document/d/1_qxBkV-sEhQ5h7DkjtCpT5BISV1zvdahumwD7ihaMUA/edit?usp=sharing

**Comment by meghscase** [comment]
By as is, I mean where info should go. I did make quite a few suggestions.

**Comment by mkhandekar** [comment]
@kalvinwang there is new content for the new PEUC program that launched this week that needs to be edited on the Guide. Could you prioritize this to be the first thing you do on Monday morning? 

https://docs.google.com/document/d/1HQDkapLJ7VxvCJxmbk4uGrHxHjNORjDiDi-ms_kY91Q/edit#

As usual, the changes are where I've “suggested” changes in the google doc, and I’ve also highlighted where those “suggested” changes are in yellow highlighter. 

Please reach out on Monday if you have any questions!

**Comment by mthong** [comment]
Hi @kalvinwang, I conducted a manual comparison of the [active draft document](https://docs.google.com/document/d/1HQDkapLJ7VxvCJxmbk4uGrHxHjNORjDiDi-ms_kY91Q/edit?usp=sharing) and the production site. I tagged you in a few comments in the Google doc where I noticed differences.
