### ISSUE TITLE
Resume deploys

### ISSUE THREAD

**Issue by sharonwarner** [cagov/unemployment#208]
We stopped deploys for a bit because we needed approval before the Spanish content got deployed to prod. We now need to resume deploys, but since it's been awhile since we deployed, we should do some extra testing on the staging environment to make sure everything is working as expected.

1) Run an accessibility scan
1) Confirm the site displays in IE
1) Confirm the "Change Language" button works in IE (it's already been tested on Edge)
1) Confirm the site displays on mobile devices

**Comment by kalvinwang** [comment]
1. Lighthouse accessibility scan remains at 92
2. Confirmed working in IE11
3. Confirmed new dropdown works in IE11
4. Confirmed working on Mobile Safari
