### ISSUE TITLE
Frontend logging and error alerting

### ISSUE THREAD

**Issue by sharonwarner** [cagov/unemployment#212]
We need to have alerting setup for frontend Javascript errors that prevent the page from rendering correctly. CDT doesn't currently have a default tool for this. Ideally, we should write to the Azure logs and then setup an alert on keywords from the logs. If that solution doesn't work for some reason, we should look into Sentry or Mixpanel.

**Comment by kalvinwang** [comment]
It looks like Application Insights for web pages will do what we need, it can be inserted as a header  JS snippet or added as a library from npm. @sharonwarner do you [have permissions for it on our App Service](https://docs.microsoft.com/en-us/azure/azure-monitor/app/javascript)? I don't. Guess we'll need to ask CDT to enable it for us.
