### ISSUE TITLE
Content | Certification | Review content (landing page and questions) and help desk

### ISSUE THREAD

**Issue by meghscase** [cagov/unemployment#218]
- [x] Review app landing page content in [Figma](https://www.figma.com/file/voyh0E7h1WmzvpUWs8bL0g/CA-UI-Recertification?node-id=0%3A1)
  * Suggestions will be found [here](https://docs.google.com/document/d/16dSDKsBedNZO0PgovUucHSItXZp0nofDQUmGUK95W7o/edit#)
- [x] Review questions and help text in [spreadsheet](https://docs.google.com/spreadsheets/d/1qFquPBizcO0B5gSykv51R1XEj3ShGD_beJbqEK_vkfo/edit#gid=1814024487)

**Comment by mkhandekar** [comment]
- [Retroactive Certification – Questions and Help Text - ACTIVE DRAFT](https://docs.google.com/spreadsheets/d/1qFquPBizcO0B5gSykv51R1XEj3ShGD_beJbqEK_vkfo/edit#gid=1814024487)
- [Retroactive Certification - Application Content – ACTIVE DRAFT](https://docs.google.com/document/d/1WdMsc_nId5PH7qFLwCFlTImLU1SiQ0QhtJA3OfYBNbo/edit#heading=h.jhwsikwuy7l2)
