### ISSUE TITLE
Add a feature toggle

### ISSUE THREAD

**Issue by sharonwarner** [cagov/unemployment#226]
Both the retroactive certification app and the guide are going to live in the same repository. We need to be able to deploy guide updates while not exposing the retroactive certification app to the public before it's ready. 

- [ ] Research feature toggle libraries for Node/React applications hosted in Azure
- [ ] Choose one
- [ ] Implement the logic such that the retroactive certification app is visible in dev and staging environments but not production

**Comment by idealisms** [comment]
If we're going to continue to auto-deploy, I think staging should match prod, so it's easy to tell if we broke something on the guide.

That said, we probably do need retro-certs in some sort of staging environment. After researching feature toggle libraries, I'll look into getting a second staging environment set up for retro-certs.

**Comment by idealisms** [comment]
Ok, this seems fine:
https://github.com/FredKSchott/fflip

It also has an express middleware, but that's probably overkill unless we want to do cookie based feature flipping.

Here's my current thinking:
We have a feature toggle like retroCertsEnabled. When false, we remove any POST handlers on the server side. On the client side, we don't load the routes to any retro-cert pages.

In prod, retroCertsEnabled is false. In dev and staging, retroCertsEnabled is true. I think that should be safe. It's still possible to see code for the retro certs pages in the client JS, but I don't think that's a secret.

To set different staging and prod feature toggles, we probably need to set an environment variable differently between the two. I will probably need some help with that.

**Comment by kalvinwang** [comment]
Re: the environment variable, I just came across the [Settings > Configuration > Application Settings page](https://portal.azure.com/#@digitalca.onmicrosoft.com/resource/subscriptions/005fa005-b981-47d8-8b39-5b82adf6569c/resourceGroups/RG-CDT-PUB-VIP-BNSCN-W-P-002/providers/Microsoft.Web/sites/AS-CDT-PUB-VIP-BNSCN-WL-P-002/configuration) where env variables can be read/written in Azure. I don't have permission to view or edit, I'm guessing @sharonwarner doesn't either? We may want to ask CDT for that.

**Comment by idealisms** [comment]
Hmm, I think the environment variable needs to be set in the [docker environment](https://docs.docker.com/engine/reference/commandline/run/#set-environment-variables--e---env---env-file). So for staging, we will want to add --env ENABLE_RETRO_CERTS=1 to the docker run command. Maybe that's what Application Settings does.
