### ISSUE TITLE
Add page routing

### ISSUE THREAD

**Issue by sharonwarner** [cagov/unemployment#227]
The retroactive certification app requires more complicated routing logic than the guide. We should implement the repo routing to match the VT model.

Some files to reference in the VT app:
- src/data/routes.js
- src/routes/single-page-app.js (lines 16-19)
- src/client/App.js (line 75)
- src/client/pages/index.js (lines 24-28)

Possibly move guide section components to pages?

Things to keep in mind:
1) We can no longer redirect all traffic to /guide
2) Let's start with unemployment.edd.ca.gov/retroactive-certification for the URL.
3) How do we link between the guide and the retro-certification app? Do we need to link between them?
4) Do we need to update any DNS records?

**Comment by idealisms** [comment]
My understanding is that for src/data/routes.js, we want an entry per URL. The question is if we want a different component or if we can still share a single component for this. So either:

const routes = {
  guidePageBenefits: {
    path: "/guide/benefits",
    component: "GuidePageBenefits"
  },
  guidePageBeforeYouApply: {
    path: "/guide/before-you-apply",
    component: "GuidePageBeforeYouApply"
  },
  ...
}

OR

const routes = {
  guidePageBenefits: {
    path: "/guide/benefits",
    component: "GuidePage"
  },
  guidePageBeforeYouApply: {
    path: "/guide/before-you-apply",
    component: "GuidePage"
  },
  ...
}

I suspect we can make the latter work, so I'll try that first.

**Comment by sharonwarner** [comment]
That sounds great! I agree the later is preferable.
