### ISSUE TITLE
Tech spec: Authentication

### ISSUE THREAD

**Issue by sharonwarner** [cagov/unemployment#228]
We've come to some agreement wrt how we're going to authenticate users. When users arrive at the retroactive certification homepage, they'll be asked to supply their last name, eddcan id, ssn, and potentially one other field that EDD is going to supply. ISO has also requested that we include a reCAPTCHA to prevent spam. 

We need to write a tech spec to determine how we'll implement this logic. The tech spec should cover the following topics plus any others that become relevant:
- How can users "logout" or fill out the form for a second user?
- Is a reCAPTCHA sufficient for preventing brute force attacks?

**Comment by kalvinwang** [comment]
From #229, should've posted here: "I've seen a TON of anecdotal complaints about reCAPTCHAs both being extremely frustrating for many humans, as well as no longer being as helpful for their intended purpose of stopping bots (unless combined with other measures). Can we investigate reCAPTCHAs and if there are better alternatives to fulfilling the need ("prevent spam")? I'm also curious what preventing spam means to them in this context."

@idealisms response: "I think the main concern is people trying to brute force auth credentials (SSN/EDDCAN). Is reCAPTCHA no longer effective in stopping bots from doing that?"

**Comment by idealisms** [comment]
https://docs.google.com/document/d/1tselLo_3UOR0VnBsomlfv5NbvLCEbwVufrybN_GlIQQ/edit#
