### ISSUE TITLE
Certification | Authentication designs and frontend implementation

### ISSUE THREAD

**Issue by sharonwarner** [cagov/unemployment#229]
We've come to some agreement wrt how we're going to authenticate users. When users arrive at the retroactive certification homepage, they'll be asked to supply their last name, eddcan id, ssn, and potentially one other field that EDD is going to supply. ISO has also requested that we include a reCAPTCHA to prevent spam.

We'll need designs for a login page, potentially a login success page (though I think just the first page of the form would suffice), a logout button (potentially in the headers?), and a logout success page.

Design, @nguyen-tina: `2 pts`
Eng: `3 pts`

**Comment by kalvinwang** [comment]
I've seen a TON of anecdotal complaints about reCAPTCHAs both being extremely frustrating for many humans, as well as no longer being as helpful for their intended purposes of stopping bots (unless combined with other measures). Can we investigate reCAPTCHAs and if there are better alternatives to fulfilling the need ("prevent spam")? I'm also curious what preventing spam means to them in this context.

**Comment by idealisms** [comment]
I think the main concern is people trying to brute force auth credentials (SSN/EDDCAN). Is reCAPTCHA no longer effective in stopping bots from doing that?

**Comment by sharonwarner** [comment]
There's a separate ticket, #228, to write a tech spec for the authentication implementation. I just added a note on that ticket to make sure to look into reCAPTCHA's effectiveness. The three authentication tickets (#228, #230, #231) will probably need to be edited a bit after the tech spec is finished.

**Comment by mkhandekar** [comment]
Questions:
* What does an eddcan id look like?

To watch:
* ISO has also requested that we include a reCAPTCHA to prevent spam. Since our engineering team here is saying that there is still some technical research to be done on this, @nguyen-tina I would ignore this requirement for now.

**Comment by idealisms** [comment]
From [this faq](https://www.edd.ca.gov/unemployment/FAQ_-_UI_Online.htm):

> The EDD Customer Account Number is a unique, ten-digit account number assigned by the Employment Development Department.

**Comment by mthong** [comment]
Should this ticket include login error messages for people who don't login successfully? 

These are the user stories currently in the product spec. 
- As a claimant who doesn’t need to retroactively certify, I want to be told that I don’t need to retroactively certify after attempting to authenticate, so that I can have peace of mind. 

- As a claimant who can’t successfully authenticate, I want to know what to do if I’m not sure if I need to retroactively certify or not. (I'm not positive we need this one, but I feel like people will want to know who to ask for help) 

- As a claimant who has already retroactively certified, I want to receive a message telling me that I've already answered the questions and don’t need to answer the questions again.

**Comment by sharonwarner** [comment]
There isn't really any way for us to know the difference between claimants who don't need to retroactively certify and claimants who can't successfully authenticate. Either the login credentials will match an entry in the list or they won't. Can we combine those two cases with one error message? 

I think the user story for the claimant who has already retroactively certified should be covered in a separate ticket. That requires the data we collect from the form, and we haven't built that yet.

**Comment by mkhandekar** [comment]
Related to Michelle's second bullet there:

> As a claimant who can’t successfully authenticate, I want to know what to do if I’m not sure if I need to retroactively certify or not. (I'm not positive we need this one, but I feel like people will want to know who to ask for help)

Are we sending an email to people who don't have a BPO account (and they have applied via paper form, etc)? If yes, and they follow the link, what happens if people don't have a BPO account? What's the alternative?

**Comment by idealisms** [comment]
> Are we sending an email to people who don't have a BPO account (and they have applied via paper form, etc)? If yes, and they follow the link, what happens if people don't have a BPO account? What's the alternative?

Oh, what are we using BPO accounts for? Is email the 4th data field we're using?

Either way, I think we don't have emails except for people who have a BPO account. AFAIK, the paper form and those that apply via the phone don't provide an email address.

**Comment by nguyen-tina** [comment]
Update: Designs have been completed, just need iteration on error messaging. 
![0 2 – Sign in – Logged out](https://user-images.githubusercontent.com/17328158/83189777-75b32200-a0ff-11ea-9c80-0e335c79ab1f.png) I think I will turn this over to @meghscase for content!
