### ISSUE TITLE
Authentication backend login implementation

### ISSUE THREAD

**Issue by sharonwarner** [cagov/unemployment#230]
https://docs.google.com/document/d/1tselLo_3UOR0VnBsomlfv5NbvLCEbwVufrybN_GlIQQ/edit#

- Add a json object to the repo with some fake data containing hashed SSNs, eddcans, and hashed last names
- Build login API '/login' that will accept an SSN, eddcan, and last name, hash the SSN and last name, and return a success message along with an authentication token if the three fields match a record in the json object, and an error message if the three fields don't match a record

**Comment by idealisms** [comment]
Does this ticket cover session management?

Have you used anything in the past for session management? Looks like there's [expressjs/session](https://github.com/expressjs/session), but we'll also need storage for managing sessions (redis or another cosmos table?).

**Comment by idealisms** [comment]
Passing this on to Sharon to implement the recaptcha check.

Maybe we use a new issue for hooking this up to the database.
