### ISSUE TITLE
Time estimation for detailed confirmation page(s)

### ISSUE THREAD

**Issue by mthong** [cagov/unemployment#255]
At a 6/1 timeline meeting, EDD business owner requested that the Nava team estimate the design and engineering level of effort for more detailed confirmation pages(s). 

There are two different points in the app where a more detailed confirmation page would be useful: 
(a) Entry confirmation page: Appears after the user logs back in, and would especially be useful to customer support scenarios 
(b) Post-submittal confirmation page: Appears immediately after submitting

Both of these pages would show the same information: for each week that the claimant retroactively certified, it would show their full answers to each question (yes/no + income details). 

**Deliverables for this task**
From Design:  
(a) estimated # of days to design the entry confirmation page
(b) estimated # of additional days to design the post-submittal confirmation page (it seems like this page would be very similar but there may be some differences)
(c) even if this feature were to be released after the pilot launch, can this design be done before launch, so engineering can begin as soon as possible after launch. 

From Engineering
(a) estimated # of days to implement the entry confirmation page  
(b) estimated # of additional days to implement the post-submittal confirmation page 

This estimate will be used by EDD UI team to make a decision on whether it is worth the time impact to do this before launch, after launch, or not at all.

**Comment by sharonwarner** [comment]
We're going to display the same confirmation page in both cases. So once this information is added to the post-submittal confirmation page, it will immediately show up on the entry confirmation page. I think it's ~1.5 days of engineering work to implement both the English and the Spanish.

**Comment by mkhandekar** [comment]
For design, we need 1 day. I think we should do it before launch so that we can do some testing on a more detailed page (even if it's not implemented before launch)

**Comment by mkhandekar** [comment]
Closing this because we estimated the time.
