### ISSUE TITLE
Update deploy process

### ISSUE THREAD

**Issue by kalvinwang** [cagov/unemployment#263]
Updated ticket: We've updated the deploy process to no longer automatically deploy at 9am. Instead, the process sends an email to folks who are able to approve deploys at 9am. The deploy will only be triggered when/if somebody approves the deploy.

We need to 1) decide what we want for the deploy process, 2) work with CDT to implement the new logic, and 3) document the new process.

------------------

On 6/3: it looks like azure is deploying both of the releases we merged to staging yesterday, to production, in sequence. i’d expect it to instead only merge the more recent release to staging and skip the older one. 

![image](https://user-images.githubusercontent.com/82277/83771563-64629c00-a650-11ea-95da-bd68689e0eb9.png)

older release from yesterday:
![image](https://user-images.githubusercontent.com/82277/83771573-66c4f600-a650-11ea-907b-96c499456ea8.png)

newer release from yesterday:
![image](https://user-images.githubusercontent.com/82277/83771577-67f62300-a650-11ea-8064-2daec18d048f.png)

**Comment by kalvinwang** [comment]
Shamal says it’s operating as intended, so we may be mistaken about it ever deploying only the most recent staging release to production. The other option he’s aware of is, we can disable automatic 6am deploys, and manually approve the most recent staging release to be deployed.
We can investigate more to see if there’s a better alternative

**Comment by idealisms** [comment]
FWIW, I don't love the automatic 6am deploys. It seems safer to me to manually deploy to prod (when you are certain someone is watching).

**Comment by kalvinwang** [comment]
@idealisms it was actually being deployed automatically at 9AM ET because that's the lowest-traffic time in CA when we're certain that someone is paying attention in ET, between me and Sharon :) moot point now that the retrocert app is live and we're not automatically deploying!

**Comment by kalvinwang** [comment]
@sharonwarner I'm closing this ticket but please reopen if it's still relevant!
