### ISSUE TITLE
Format landing page after login

### ISSUE THREAD

**Issue by sharonwarner** [cagov/unemployment#279]
<img width="501" alt="Screen Shot 2020-06-09 at 11 28 55 AM" src="https://user-images.githubusercontent.com/4306128/84167574-6d82ad00-aa44-11ea-9ddb-3ca5e8e07700.png">

**Comment by idealisms** [comment]
You can double check with Sharon, but I would rename this from /landing to /weeks.

**Comment by idealisms** [comment]
I can do this on Monday if you want. Can we get an updated mock?

**Comment by nguyen-tina** [comment]
![1 1 – Home with Sign in Success](https://user-images.githubusercontent.com/17328158/85303083-0a4b3e80-b478-11ea-9827-da4945a97c35.png)

You can also find it in the [figma, labeled under 1.0](https://www.figma.com/file/voyh0E7h1WmzvpUWs8bL0g/CA-UI-%E2%80%93-Retroactive-Certification-%E2%80%93-UI?node-id=458%3A88)!

**Comment by idealisms** [comment]
Also update the formatting of dates on the confirmation page.
