### ISSUE TITLE
Login error handling

### ISSUE THREAD

**Issue by sharonwarner** [cagov/unemployment#281]
The user should be required to fill out all 4 fields before submitting the form. 

If a user clicks the submit button without filling out all 4 fields, the missing fields should be highlighted in red, and we should display an error message.

<img width="786" alt="Screen Shot 2020-06-16 at 2 04 11 PM" src="https://user-images.githubusercontent.com/4306128/84811063-4e52c500-afda-11ea-9d44-1e91aaaaea59.png">

**Comment by meghscase** [comment]
### **Draft error messages**

**If  1️⃣ a user attempts to enter information, but is not part of the group of people who need to retroactively certify, or 2️⃣ a user incorrectly enters their last name.** 

“We couldn’t find your information. Make sure the information you entered is correct. If it is correct, you do not need to certify.”

**If the claimant needs to retroactively certify, but types some of their information incorrectly: 
If the EDDCAN does not match the SSN:** 
“The EDDCAN you entered isn’t tied to your Social Security Number. Please re-enter and try again.”

**If the SSN does not match the EDDCAN:** 

“Your Social Security Number isn’t tied to the EDDCAN you entered. Please re-enter your Social Security Number and try again.” 

**If the application is missing a required field:**

“It looks like you missed some information. Please fill out all fields and try again.”

**Comment by meghscase** [comment]
@sharonwarner See above.

**Comment by meghscase** [comment]
### UPDATED error messages. 
Leaving draft in case we go back to it. 

**If  1️⃣ a user attempts to enter information, but is not part of the group of people who need to retroactively certify, or 2️⃣ a user incorrectly enters their last name.** 
“Review and verify the information you entered is correct.”

**If the claimant needs to retroactively certify, but their EDDCAN does not match the SSN:**

“Review and verify the information you entered is correct. Refer to the Employment Development Department Customer Account Number Notification, DE 5614 that you received in the mail for more information on your EDDCAN.”	

 **If the claimant needs to retroactively certify, but their SSN does not match the EDDCAN:**
“Review and verify the information you entered is correct.”

**If the application is missing a required field:**

“It looks like you missed some information. Please fill out all fields and try again.”

cc: @sharonwarner

**Comment by idealisms** [comment]
Although we no longer have partial match error messages, we do need an error message for reCAPTCHA. If the does the reCAPTCHA and waits for more than 2 minutes, the login will fail and they will have to check the box again. We need an error message to ask the user to check the box and press submit again.

**Comment by jlechowicz** [comment]
Leaving this here for future reference
![image](https://user-images.githubusercontent.com/5550848/84810930-ae913900-afd1-11ea-876f-2c627054046f.png)

**Comment by meghscase** [comment]
Thanks, Tony. I was thinking that would be covered by reCAPTCHA.

Please check the box next to "I'm not a robot" to continue.

**Comment by idealisms** [comment]
Oh, one more error message:

After the session timeout of 30 min, we kick the user back to the login screen and show them an alert that they have been logged out. What should that text say?

**Comment by meghscase** [comment]
We logged you out after 30 minutes of inactivity. Please provide your
information again to certify your weeks.


QUESTION: Could we do one that warns them they are about to be timed out a
minute or so before? Or is that too much effort at this point?

**Comment by meghscase** [comment]
For some reason what I responded with earlier isn't showing up here, so
including it again just in case ...

Message: We logged you out after 30 minutes of inactivity. Please provide
your information again to certify your weeks.

QUESTION: Can we warn them when they are close to the timeout or is that
too much effort at this point?

**Comment by idealisms** [comment]
I've filed issue #314 for a warning dialog. I agree, it would be nice to do.
