### ISSUE TITLE
Create retrocert form subheader component

### ISSUE THREAD

**Issue by sharonwarner** [cagov/unemployment#283]
Inputs:
- headerText

<img width="311" alt="Screen Shot 2020-06-09 at 12 09 00 PM" src="https://user-images.githubusercontent.com/4306128/84172446-0536ca00-aa4a-11ea-88ef-4bb529b0f42b.png">

**Comment by idealisms** [comment]
Do we want the language toggle? I thought we were launching without Spanish for a week (June 29-July 6).

Also, we should update the page title as well (maybe in this component). Our pages all have "Guide to applying for unemployment benefits" on it.

**Comment by mthong** [comment]
We are launching with Spanish. The Spanish translation will be done early next week, and we are implementing Spanish at the end of next week (June 22-26).
