### ISSUE TITLE
Create page component to be displayed per week

### ISSUE THREAD

**Issue by sharonwarner** [cagov/unemployment#284]
Requires #282 

- Display component for each week
- Component should be connected to the React state (expected format can be found [here](https://docs.google.com/document/d/1EBbeS2uyv1rvSTGbc9LoRT3Gt8zcgn8T2v_syvE5KxY/edit#bookmark=id.h1avvl89hdza))

**Comment by idealisms** [comment]
The plan is to have /retroactive-certification/certify/2020-03-14 load a specific week to certify and show the form. The button on the bottom will navigate to the next week.

**Comment by idealisms** [comment]
The route and page exists, but we need to fill in the components on it.

**Comment by idealisms** [comment]
Note that there's also issue #285, which is for the income logic. I think the remaining work for this issue is:
- Creating questions 1-5.
- Saving data into react state.
- Validating the form fields.
- Submit logic on the last week.

Question 6 and the income logic is all part of #285.

**Comment by idealisms** [comment]
Still need to add validation and submit logic. Going to work on issue #285 first, then come back to this.

**Comment by idealisms** [comment]
Still need to submit real data.

**Comment by idealisms** [comment]
Sharon is working on submitting real data. I think this is part of issue #286. Going to close out this bug.
