### ISSUE TITLE
Format confirmation page

### ISSUE THREAD

**Issue by sharonwarner** [cagov/unemployment#287]
<img width="367" alt="Screen Shot 2020-06-09 at 12 36 50 PM" src="https://user-images.githubusercontent.com/4306128/84175390-ea665480-aa4d-11ea-9d52-e830ce16004c.png">

Update login logic such that if the user has already certified, they are routed to this page.

**Comment by idealisms** [comment]
I will put this at /retroactive-certification/confirmation.
