### ISSUE TITLE
Format successful sign in page

### ISSUE THREAD

**Issue by sharonwarner** [cagov/unemployment#289]
Requires #282 

<img width="439" alt="Screen Shot 2020-06-09 at 12 41 43 PM" src="https://user-images.githubusercontent.com/4306128/84175926-a6278400-aa4e-11ea-9802-0abc41084887.png">

**Comment by idealisms** [comment]
I'm going to put this at /retroactive-certification/what-to-expect. I'm also not going to put the language switcher at this time.

Are we showing the user's last name? I'll add it for now, but I thought we were planning on not showing anything that the user typed in.

**Comment by idealisms** [comment]
Note: We may need to remove the last name. If the data is provided the way recommended by ISO, we won't know the user's last name (or EDDCAN).
