### ISSUE TITLE
SSN field usability updates

### ISSUE THREAD

**Issue by sharonwarner** [cagov/unemployment#297]
- Dashes should be input automatically
- Users can only enter numbers
- Design should look like 1a and 1b attached in a comment below

**Comment by nguyen-tina** [comment]
Tina to put together a mock for toggling anonymity

**Comment by nguyen-tina** [comment]
Hello! 

![SSN](https://user-images.githubusercontent.com/17328158/85064906-429e0480-b17a-11ea-93b4-d802c194d19f.png)

After peeking at [some thinking done by USWDS](https://github.com/uswds/uswds/issues/986), I think we should move forward with the best-case scenario of 1a and 1b, where we normalize the input before sending it to the backend as Tony mentioned above. This is with the intent to help users input their SSNs anonymously and easily.

If we are unable to go with 1a, I'd suggest 2a. Would try to go for 1b over 2b as much as possible, time permitting.

**Comment by nguyen-tina** [comment]
Dashes should be input automatically; the users will not be able to input dashes.

**Comment by jlechowicz** [comment]
Update text to read "Hide SSN/Show SSN"
Remove bold formatting of link button

**Comment by jlechowicz** [comment]
Created PR [#332](https://github.com/cagov/unemployment/pull/332)
