### ISSUE TITLE
Time out warning modal at 25 minutes

### ISSUE THREAD

**Issue by idealisms** [cagov/unemployment#314]
Currently we just log out the user after 30 minutes expire. It would be nice to give them a warning that it is about to happen.

Some details to work out:
- How long before they are logged out? Is 1min enough time?
- How do we show the user? Maybe an in page dialog with a button to extend their session for 30 more minutes?

Doing an in page dialog is probably a 1 pt task. We could do an annoying javascript dialog with less effort.

**Comment by mkhandekar** [comment]
Hi @idealisms, a heads up that we will be using this ticket to track both design and eng work related to this. We still have to prioritize this feature with EDD. 

--

Post-MVP feature, per Product Spec for Retroactive Certification.

User value: medium
Business value: X
Level of effort: X

**Comment by mkhandekar** [comment]
@nguyen-tina I had posted this in our Portal time doc, but surfacing here also: https://github.com/alphagov/govuk-design-system-backlog/issues/104

**Comment by mkhandekar** [comment]
Proposal is being worked on here: https://docs.google.com/document/d/1ruwdjvf1g1gXLl0p8Yk5sDX-DLYQcxdtMkxAyHHuHSc/edit

**Comment by mkhandekar** [comment]
Proposal has been approved and implemented.

**Comment by sharonwarner** [comment]
Reopening for engineering work.
