### ISSUE TITLE
Perjury check

### ISSUE THREAD

**Issue by sharonwarner** [cagov/unemployment#320]
![Screen Shot 2020-06-19 at 2 21 53 PM](https://user-images.githubusercontent.com/17328158/85168401-5445e180-b238-11ea-808c-c3774febb4e2.png)
![Screen Shot 2020-06-19 at 2 22 07 PM](https://user-images.githubusercontent.com/17328158/85168405-55770e80-b238-11ea-9590-cd1cbbd7a2d6.png)

Updated 6/19/20 by Tina

**Comment by idealisms** [comment]
I'm going to do the validation first, since it's needed for this checkbox too.

**Comment by idealisms** [comment]
The mock has changed from what I implemented. It should be pretty easy to fix (only text changes).

**Comment by nguyen-tina** [comment]
Whooops, sorry! Next time I'll leave the update as a comment
