### ISSUE TITLE
Improve form validation errors on certification page 

### ISSUE THREAD

**Issue by idealisms** [cagov/unemployment#328]
If you try to submit on the certification page with some missing data, we highlight text fields with a red ! and Yes/No questions. A few problems:

- The Yes/No highlighting is subtle. We probably want some better more visible styling.
- There's no communication to the user what the problem is. Maybe there should be an alert?
- There's no error text next to each form field.
- We don't scroll to the first field with an error.

I think we need some guidance from design and then implement it.

**Comment by idealisms** [comment]
This can probably be done after Sprint 5, although UAT will probably notice.

**Comment by nguyen-tina** [comment]
"in-line" error for acknowledgement on final certification page

![3 1 – Last Certifying Week](https://user-images.githubusercontent.com/17328158/85339672-a2661980-b4b2-11ea-816e-71ba182a9dbd.png)

**Comment by idealisms** [comment]
Thanks for the mocks! I'm going to implement this today.
