### ISSUE TITLE
Update login page to use DOB

### ISSUE THREAD

**Issue by sharonwarner** [cagov/unemployment#330]
Update test data hashes and [documentation](https://docs.google.com/document/d/1k8QJojJ855sdbSXRrKqvnCpLAnoAWGKFxoY84zsA4UI/edit#) to use DOB

**Comment by nguyen-tina** [comment]
![0 1 – Sign in](https://user-images.githubusercontent.com/17328158/85329453-8eb1b780-b4a0-11ea-951c-49265560e466.png)
