### ISSUE TITLE
Dropdown text is cut off in PUA question 7 

### ISSUE THREAD

**Issue by sharonwarner** [cagov/unemployment#331]

**Comment by jlechowicz** [comment]
@sharonwarner @nguyen-tina Given that we are dealing with long pieces of text here, are we locked in to having to use a dropdown for the control?
I'm wondering if using a radio button list would be better here?

**Comment by nguyen-tina** [comment]
I'm ok with trying a radio button-- so long as all the text is visible to the user and they can only select one option, I think it makes sense.
