### ISSUE TITLE
Set production live

### ISSUE THREAD

**Issue by sharonwarner** [cagov/unemployment#356]
- Confirm DB has been setup (should be done as part of #262) 
- Flip feature toggle
- Submit retro-certification form for one of the test users
- Update the EDD input test file to include all the edge cases, run the import script on their input test sample file and upload the result to the prod db, and test users from the sample file on prod
- Turn off automatic prod deploys
- Let Michelle know we're ready!

**Comment by idealisms** [comment]
Also, we hardcoded the production URL into the client JS. We need to remove that check.

**Comment by idealisms** [comment]
We're live!

**Comment by idealisms** [comment]
For documentation purposes: The deploy to prod went smoothly, but recaptcha wasn't working. We forgot to add the key to prod and once added, everything was fine. We should have had recaptcha key on our launch checklist (or have done it in advance)!
