### ISSUE TITLE
Timeout isn't redirecting user

### ISSUE THREAD

**Issue by sharonwarner** [cagov/unemployment#368]

**Comment by idealisms** [comment]
Disucssion from slack:

jimdelloso Today at 5:16 AM
30 timeout testing:  Stayed on start page for 30 minutes.  Click Start Certifing. Blank page appeared.  Attempted to browser reload.  Page said Loading...  Never reloaded.
10 replies

kalvin  7 hours ago
interesting, we might need to implement redirect-to-landing-page-when-loading-other-page-while-logged-out…

sharon  6 hours ago
interesting, thanks jim... i wonder why the start page didn't redirect you

jimdelloso  6 hours ago
I just posted about Jarvis.  I think this may be related.

jimdelloso  6 hours ago
The logout occurred at 752am this morning if you need to look at any logs.

sharon  4 hours ago
looking into this a bit further now!

sharon  18 minutes ago
@Tony Chang https://github.com/cagov/unemployment/issues/368

sharon  18 minutes ago
i wasn't able to replicate the issue locally

Tony Chang  5 minutes ago
The page not loading was related to the Jarvis account having some bad data. If the session timer triggered, you would have been redirected to the login page. So either the timer didn't fire at all (bug), or the navigation happened before the timer fired.

jimdelloso  4 minutes ago
Sounds good to me.

Tony Chang  4 minutes ago
So it might not be a bug in the session timer. I would see if being on the page for a little more than 30 min doesn't log you out.

**Comment by idealisms** [comment]
It sounds like to me that the bug was with the user data on the server and the session timer is working as expected. I'm going to tentatively close this issue for now, but if we see a case where after, e.g., 31 minutes there was no redirect, please reopen or file a new issue.
