### ISSUE TITLE
Testing edge case

### ISSUE THREAD

**Issue by sharonwarner** [cagov/unemployment#373]
Edge case test - a final item that we didn't discuss at standup -> for @kalvin @sharon, cc @jimdelloso. Alex wants to be able to test the fact that a claimant who is listed for two different programs (UI and PUA) in the EDD database will actually see just a PUA form. Can we do this with an existing claimant in Deloitte's test file? E.g. show her the test entry from Deloitte, then have her enter that information into our app and see that the person gets the PUA form?

- Kalvin to import test users to staging DB
- We'll confirm we can log in as each of those users

**Comment by kalvinwang** [comment]
I processed EDD's test data file and verified that the output correctly assigned PUA to weeks associated with both UI and and PUA. Then I imported the output's four test users into the staging DB and tested with Doe and Guzmán and confirmed that we can log in with them, and that the PUA form is shown for Doe for the first week which is marked as both UI and PUA in the original test data file.
