### ISSUE TITLE
What baseline data do we have on on the main causes of "unclean" applications?

### ISSUE THREAD

**Issue by mthong** [cagov/unemployment#39]
Our primary goal for the "how-to" guide is to maximize the percentage of "clean" applications received through UI Online. Clean applications are processed automatically, which increases the speed at which claimants get their benefits, and reduces manual work for the EDD. 

To determine whether the how-to guide we develop is impact the percentage of "clean" applications, we need:
* Baseline data on what percentage of applications were clean for a given time period (E.g. one week post-covid but pre-screener). 
* If possible, a breakdown by percentage of top reasons why applications were not clean

We also need to understand what other reasons result in an application being manually processed even if the application is clean.

**Comment by danachis** [comment]
From email from @ehysen on Friday: 

_Updated list that I drafted:

1. SSA and/or DMV validation is successful without requiring further documentation
2. For non-citizens, SAVE validation is successful without requiring further documentation
3. For UI claims, all employers entered by the claimant have provided data in the base wage file for that claimant
4. Claimant does not already have a UI claim or exhausted benefits for the year (for UI)
5. Claimant answers yes to all required attestations

Per EDD: "I don’t think we have a definitive list for clean claim scenarios for either UI or PUA in a standalone document form (have them as business rules in our design docs), but you have the main items below." So I'd consider this the list._

**Comment by danachis** [comment]
Those are the _reasons_, of course. ^^^  Not the data. It's not clear that they're actually tracking the reasons that claims are kicked out for manual review.
