### ISSUE TITLE
Mobile pages not auto-scrolling after successful login

### ISSUE THREAD

**Issue by KevinJBoyer** [cagov/unemployment#415]
On 6/26, on Samsung Galaxy S7 Chrome: After logging in successfully, the next page loads without scrolling back to the top, so I land in the middle of the page's content. Will post screenshots shortly.

**Comment by KevinJBoyer** [comment]
![Screenshot_20200626-163507_Chrome](https://user-images.githubusercontent.com/31424131/85898908-2417b900-b7cb-11ea-9c72-630f5189c0be.jpg)
The clicking "Find Me" results in...
![Screenshot_20200626-163514_Chrome](https://user-images.githubusercontent.com/31424131/85898909-2548e600-b7cb-11ea-9ae9-19e124841013.jpg)

**Comment by mkhandekar** [comment]
Same behavior on iPhone 7. Here's a screenshot.

![Image from iOS](https://user-images.githubusercontent.com/1598889/85900558-a69d7a00-b7c5-11ea-96a3-77c5a825efed.png)

**Comment by KevinJBoyer** [comment]
Meghana found this on iPhone too. For me, on Android, it happens a second time when I click through to the first week, but the transition between weeks works fine.

**Comment by idealisms** [comment]
There's this page. Should be pretty straightforward and a big usability improvement on mobile.

https://reacttraining.com/react-router/web/guides/scroll-restoration
