### ISSUE TITLE
SSN formatting as 123-0#-####

### ISSUE THREAD

**Issue by jdelloso** [cagov/unemployment#417]
When using 123-00-0000 as an SSN, the system only shows 123-0#-####.

**Comment by KevinJBoyer** [comment]
This may not be an error -- SSNs cannot contain "00" for the middle two digits. I played around and triggered similar issues, and I think they're all just preventing invalid SSNs from being typed in. https://www.ssa.gov/history/ssn/geocard.html

**Comment by idealisms** [comment]
I think this is working as intended, but feel free to reopen if it's still a problem.
