### ISSUE TITLE
Compile data for daily "launch week" report on retro cert 

### ISSUE THREAD

**Issue by mthong** [cagov/unemployment#439]
Key things to report:

For each day: 
- How many people landed on front page of app (Google Analytics)
- How many people have logged in  (Google Analytics - 2nd page of form) 
- How many people have completed the form (Google Analytics - confirmation page) 
- How many people have timed out (Google Analytics) 
- Error rates: Internal server errors, etc. (Azure) 
- How many people have logged in and failed (@kalvinwang to check front end logging)

From communications partners:
- # of people who've received a communications and by channel (email vs SMS)

- Time of last deploy
- Code security scan (confirm with @sharonwarner that this is currently active as part of deployment process)

**Comment by idealisms** [comment]
You can see the login errors [in Analytics](https://analytics.google.com/analytics/web/#/report/content-event-events/a3419582w42030724p216222309/explorer-segmentExplorer.segmentId=analytics.eventAction&_r.drilldown=analytics.eventAction:LoginResponse&explorer-table.secSegmentId=analytics.eventLabel&explorer-table.plotKeys=%5B%5D/).
