### ISSUE TITLE
Rename git master branch to main

### ISSUE THREAD

**Issue by kalvinwang** [cagov/unemployment#461]
Rename the master branch for this repository to main. We can take this small action to avoid perpetuating racist ideas and values, while we're also working on the bigger actions, as individuals and as a society.

> "As a black software engineer I have often felt uncomfortable with a variety of terms used throughout the industry. Terms like master/slave, blacklist/whitelist, and black hat/white hat enforce this country's belief that white is good and black is not. We can and should be better than this.
> 
> I am the product of slaves and sharecroppers from Louisiana/Tennessee so using the term master to define the default source of truth in my repos has always caused me pain. But I got used to it because it was such a pervasive term, and every time I brought up how hurtful it was to coworkers I was met with resistance. I refuse to do so any longer. Today, I have begun the process of moving to the use of main as my default branch in all of my owned repos. So i'm here to show you how to make a change that will take 3 minutes or less and make your teams more inclusive."

From: https://dev.to/afrodevgirl/replacing-master-with-main-in-github-2fjf

Github will be renaming master to main for all new repositories: https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/

Another howto: https://www.hanselman.com/blog/EasilyRenameYourGitDefaultBranchFromMasterToMain.aspx

**Comment by idealisms** [comment]
Note that we need to update the Azure pipelines that are referencing master.
