### ISSUE TITLE
Investigate and resolve: accessibility issue "Make timing clock adjustable"

### ISSUE THREAD

**Issue by sharonwarner** [cagov/unemployment#462]
Making the timing clock adjustable is recommended. Currently after inactivity you will need to start over for security purposes.   https://www.w3.org/TR/2016/NOTE-UNDERSTANDING-WCAG20-20161007/time-limits-required-behaviors.html

**Comment by mkhandekar** [comment]
Next steps:
* Clarify request, what is really being asked?
* Learn about precedence on UIO
*  Ask UIB to get agreement from ISO and then move forward

**Comment by sharonwarner** [comment]
Closing in favor of #314
