### ISSUE TITLE
Accessibility: Only allow numbers in DOB field

### ISSUE THREAD

**Issue by sharonwarner** [cagov/unemployment#463]
From EDD: Date of birth fields allow for entering any characters. Example is provided in the header but that may not be sufficient. Recommended to add the format into the fields and to make number fields if that is the criteria to follow.

We should research this recommendation before implementation. Other accessibility folks recommend the input fields that are already implemented on the site.

**Comment by idealisms** [comment]
Here's the USWDS that recommend against using a <input type=number>:
https://designsystem.digital.gov/components/form-controls/#date-input

**Comment by kalvinwang** [comment]
@idealisms it looks like the USWDS guidelines are warning against "number inputs", not against only allowing numbers to be entered in a text input field, which is what they're asking for

**Comment by idealisms** [comment]
> @idealisms it looks like the USWDS guidelines are warning against "number inputs", not against only allowing numbers to be entered in a text input field, which is what they're asking for

Oh, I guess I don't know how you would have a text input field only accept numbers other than type="number". We already validate the fields and make sure they are numbers (1-12 for month, 1-31 for day, some limits on the year) before allowing you to submit it to the server.

**Comment by sharonwarner** [comment]
We can update the event logic. Something like: 
```  
const setNoNumberDobMonth = (event) => {
  setDobMonth(event.target.value.replace(/\D/,''))
}
```

**Comment by sharonwarner** [comment]
We talked this over with the accessibility tester and determined that no updates are needed.
