### ISSUE TITLE
Add character limits for question 6 follow-up text fields

### ISSUE THREAD

**Issue by sharonwarner** [cagov/unemployment#476]
Employer Name - 500 characters
Address Line 1 - 500 characters
Address Line 2 - 500 characters
City - 100 characters
Zip - 10 characters
Total Hours - 6 characters
Gross Earnings - 11 characters
More Details - 2000 characters

**Comment by nguyen-tina** [comment]
For gross earnings, do users have to input $ or . ? Does it count as a character? Could it automatically format into currency?

**Comment by sharonwarner** [comment]
Right now, gross earnings accepts input in these formats: '$xxxxxx', 'xxxxxx', '$xxxx.xx', or 'xxxxx.xx.' All of the Xs have to be numbers. $ and . both count towards the character count.

**Comment by nguyen-tina** [comment]
Can we make the following changes? Everything else looks good to me!

Zip and Total Hours – Must be numbers or dashes (I'm sure this is already in place!)
Gross earnings – 11 characters

**Comment by sharonwarner** [comment]
Thanks Tina! Yes, those validations for zip and total hours are already in place!
