### ISSUE TITLE
Allow users to expand all sections at once for printing

### ISSUE THREAD

**Issue by kalvinwang** [cagov/unemployment#491]
Allow users to expand all sections at once for printing purposes

- Option 1a) When the user clicks the Print button, show all of the expanded sections (using javascript)
  - This won't support using the browser's print functionality, so it's not acceptable
- Option 1b) When the user clicks the Print button or uses the browser print functionality, show all of the expanded sections (using a CSS print stylesheet)
- Option 2) When the user clicks "Expand All" (text TBD), show all of the expanded sections. The user can then choose to print

**Comment by nguyen-tina** [comment]
to carry over our conversation from Slack, **I think it is useful for us to have an "Expand all" button and that we should definitely add that functionality.** It will be helpful for those who want to capture and print every answer, and for those who might just want to compare their answers week to week.

![4 0 – Confirmation Page – Expand all](https://user-images.githubusercontent.com/17328158/87990832-c9643b00-cab2-11ea-9171-8a96fd2e71d3.png)

For now, it sounds like we can move forward with Option 2 for functionality and simplicity (what the user sees is what prints). If a user accidentally printed without having any weeks shown, they can always log back in and re-print their information.

**Comment by kalvinwang** [comment]
Talked to @nguyen-tina today, we're going with option 1b!
