### ISSUE TITLE
Document and align on "north star" for improving claim status

### ISSUE THREAD

**Issue by mthong** [cagov/unemployment#550]
As a contributing team member, I want to understand what we're aiming for, so that I can work towards that goal.

**Comment by mkhandekar** [comment]
In this moment I'm curious about the expected deliverables at the end of 4 weeks. I have a general sense that it will be results from research & 1-2 prototypes, both that describe the short term and possibly longer term recommendations for claim status. Tina had another sense - that at the end of 4 weeks we would end up with a fully designed improved claim status, but I have not heard that yet from anyone, and that our research results and recommendations will lead to a future dedicated project to design an improved claim status experience. So I'd like us to clarify this, and reflect it in the North Star document.

**Comment by mthong** [comment]
North Star: 

Here are some options that emphasize different goals and metrics. 

(1) Improved claim status will reduce unnecessary calls to EDD from confused claimants, freeing up EDD staff to have more bandwidth to address other claimant needs (Emphasis is on EDD call burden) 

(2) Improved claim status will reduce claimant frustration by helping them feel more confident about what's happening with their claim and when they can expect it to be resolved. (Emphasis on claimant experience) 

(3) Improved claim status will reduce the time it takes claimants to receive their benefits by making sure that claimants clearly understand when and what actions are needed from them. (Emphasis is on speed of paying claimants - this is a stretch but is arguably the true north star of all of the UI work)

**Comment by mthong** [comment]
I believe the goal of the design sprint is to validate whether it is possible and desirable for improved claim status to meet the north star goal (whichever one we pick above, or some variant), and present recommendations and possibly prototypes for how we would do that.
