### ISSUE TITLE
Configure production alert notifications

### ISSUE THREAD

**Issue by sharonwarner** [cagov/unemployment#8]
- Confirm that production monitoring alerts are sent to Nava engineers with access to the App Service

https://portal.azure.com/#blade/Microsoft_Azure_Monitoring/UpdateVNextAlertRuleBlade/ruleInputs/%7B%22alertId%22%3A%22%2Fsubscriptions%2F005fa005-b981-47d8-8b39-5b82adf6569c%2FresourceGroups%2FRG-CDT-PUB-VIP-BNSCN-E-P-002%2Fproviders%2Fmicrosoft.insights%2Fmetricalerts%2FWhenever%20the%20http%20server%20errors%20is%20greaterthan%2060%20count%22%7D

**Comment by kalvinwang** [comment]
On Friday, Suresh said "Alerts were already configured" and Nava team will be notified. 

@sharonwarner when I visit the link in the issue, I get an "Access denied" page. I assume that doesn't happen to you, and I should request access (even though they say I've already been given the same access as you)?

**Comment by kalvinwang** [comment]
Suresh added us to a new action group, which can be notified on alerts. in terms of the actual alerts, we’ll definitely want to follow up on that. either Suresh didn’t attach the action group to any of our four (or five?) alerts, or we don’t have permission to view attached action groups, even though we’re a part of the action group.

Here's the direct link to four alerts at the Resource Group level; if you click into the app service level, you'll find the fifth alert. I haven't looked into whether these alerts make sense for us, or why they're at different levels. https://portal.azure.com/#@digitalca.onmicrosoft.com/resource/subscriptions/005fa005-b981-47d8-8b39-5b82adf6569c/resourceGroups/RG-CDT-PUB-VIP-BNSCN-W-P-002/providers/Microsoft.Web/sites/AS-CDT-PUB-VIP-BNSCN-WL-P-002/alerts
