### ISSUE TITLE
EDD research

### ISSUE THREAD

**Issue by sharonwarner** [cagov/unemployment#88]
- EDD infrastructure diagram
- Existing bottlenecks?
- Database security

**Comment by mthong** [comment]
Reference docs:
* `[ODI's certification scoping proposal](https://docs.google.com/document/d/1-oa6UoY9Z1WIOR-jYnk2BELS8cf0Dwpp9wKIc8616tk/edit?usp=sharing)`
* [DRAFT Proposed Phasing for retroactive certification app](https://docs.google.com/document/d/1gRwEFt3xY3oqrHC54ELnX061P3bbEv7nMCf4EndrkSc/edit?usp=sharing) - internal doc
* [A handful of Certification Diagrams - internal slide deck](https://docs.google.com/presentation/d/1elT2yreGU4YHjy0bJYBgsIvabYlYvTyOSexuo3sSERg/edit?usp=sharing)
* [EDD Reference Materials on Certification](https://docs.google.com/document/d/1gX4BW1M83_yXjTyVbyAnSD-XPxzm-ExRG4c1GZ7iR5o/edit?usp=sharing) - non-technical

**Comment by sharonwarner** [comment]
EDD will deliver an file with the relevant data fields to an FTP server.
