### ISSUE TITLE
Research | Certification | Secondary user research 

### ISSUE THREAD

**Issue by mkhandekar** [cagov/unemployment#91]
Due to time constraints, do a very **light pass** on secondary research. @KevinJBoyer @mkhandekar @nguyen-tina 
  - Read: [Certification - other states (from PFML).pdf](https://github.com/cagov/unemployment/files/4629902/Certification.-.other.states.from.PFML.pdf) 
  - Read (optionally, as it's a deep dive into PFML): [The certification process for PFML](https://docs.google.com/document/d/1GBAVzVsk5_m3m0yzv0B5Qxw-VYJDxE1xFVlMBbnqAO8/edit )

**Comment by mthong** [comment]
More questions:

- Where do the certification requirements come from? Are they determined by federal or state policy or both? It sounds like federal DOL has some governance over certification but I'm not sure exactly how.
- Do all states ask the same certification questions for UI or is there variation?

**Comment by KevinJBoyer** [comment]
- Are people required to continue certifying their claims even if they haven't received any benefits yet?
